import { Link } from "react-router";
import { useRecentReports } from "@/hooks";
import type { RecentReportSummary } from "@/lib/types";

// Brutalist coral shadow style
const brutalShadow = { boxShadow: "3px 3px 0 #F3787A" };
const brutalShadowSmall = { boxShadow: "1px 1px 0 #F3787A" };

/**
 * Format a date string to a readable format.
 */
function formatDate(dateString: string): string {
  try {
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return dateString;
  }
}

/**
 * Loading skeleton for a report card.
 */
function ReportCardSkeleton() {
  return (
    <div
      className="bg-white border-2 border-black p-4 animate-pulse"
      style={brutalShadow}
    >
      <div className="h-4 bg-gray-200 rounded w-3/4 mb-3" />
      <div className="flex gap-2 mb-3">
        <div className="h-5 bg-gray-200 rounded w-20" />
        <div className="h-5 bg-gray-200 rounded w-16" />
      </div>
      <div className="flex gap-2">
        <div className="h-6 bg-gray-100 rounded w-24" />
        <div className="h-6 bg-gray-100 rounded w-28" />
      </div>
    </div>
  );
}

/**
 * A single report card showing summary info.
 */
function ReportCard({ report }: { report: RecentReportSummary }) {
  return (
    <Link
      to={`/report/${encodeURIComponent(report.query_slug)}`}
      className="block bg-white border-2 border-black p-4 hover:translate-x-0.5 hover:-translate-y-0.5 transition-transform no-underline text-inherit"
      style={brutalShadow}
    >
      {/* Query title */}
      <h3 className="font-semibold text-gray-900 mb-2 line-clamp-2 lowercase">
        {report.query}
      </h3>

      {/* Meta info */}
      <div className="flex flex-wrap gap-2 mb-3 text-xs">
        <span
          className="px-2 py-0.5 bg-white border border-black"
          style={brutalShadowSmall}
        >
          {report.total_papers_used} papers
        </span>
        <span className="text-gray-500">{formatDate(report.generated_at)}</span>
      </div>

      {/* Research themes */}
      {report.research_themes.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          {report.research_themes.slice(0, 3).map((theme) => (
            <span
              key={theme}
              className="px-2 py-0.5 text-xs border border-gray-300 bg-gray-50 text-gray-600 lowercase"
            >
              {theme}
            </span>
          ))}
        </div>
      )}
    </Link>
  );
}

/**
 * Empty state when no reports are available.
 */
function EmptyState() {
  return (
    <div
      className="bg-white border-2 border-black p-8 text-center"
      style={brutalShadow}
    >
      <p className="text-gray-600 lowercase mb-2">no reports generated yet</p>
      <p className="text-sm text-gray-500 lowercase">
        start a research query above to generate your first report
      </p>
    </div>
  );
}

/**
 * Displays recently generated reports with links to view each one.
 * Brutalist design with black borders and coral shadows.
 */
export function OutputPreview() {
  const { data, isLoading, error } = useRecentReports(5);
  const reports = data?.reports ?? [];

  return (
    <section className="py-16 px-4">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl md:text-4xl font-bold text-gray-900 text-center mb-2 text-shadow-brutal lowercase">
          discover recent reports
        </h2>
        <p className="text-gray-600 text-center mb-8 lowercase">
          explore research reports generated by the community
        </p>

        {/* Loading state */}
        {isLoading && (
          <div className="grid gap-4 md:grid-cols-2">
            <ReportCardSkeleton />
            <ReportCardSkeleton />
            <ReportCardSkeleton />
            <ReportCardSkeleton />
          </div>
        )}

        {/* Error state - show message but don't break the page */}
        {error && !isLoading && (
          <div
            className="bg-white border-2 border-black p-6 text-center"
            style={brutalShadow}
          >
            <p className="text-gray-600 lowercase">
              unable to load recent reports
            </p>
          </div>
        )}

        {/* Empty state */}
        {!isLoading && !error && reports.length === 0 && <EmptyState />}

        {/* Report cards grid */}
        {!isLoading && !error && reports.length > 0 && (
          <div className="grid gap-4 md:grid-cols-2">
            {reports.map((report) => (
              <ReportCard key={report.query_slug} report={report} />
            ))}
          </div>
        )}
      </div>
    </section>
  );
}
